### ISSUE TITLE
`bel2scm.causal_graph.id_alg` is non-deterministic in its output

### ISSUE THREAD

**Issue by djinnome** [y0-causal-inference/y0#44]
If I run `test_id_alg.py` multiple times, sometimes all tests pass, and sometimes they don't:
The issue is that the string output by `causal_graph.id_alg`  is non-deterministic in its output (likely because it is iterating over sets, not ordered lists).

```python
((anaconda3-2020.11) bash-3.2$ python test_id_alg.py 

[ sum_{} P(Y|X) ]

.
[ sum_{Z} P(Y|X,Z) P(Z|X) ]

F
[ sum_{Z} P(Y|X,Z) P(Z) ]

F
[ sum_{Z} [ sum_{} P(Y|X,Z) ] [ sum_{} [ sum_{X,Y} P(X,Y,Z) ] ] ]

.
ID output: [ sum_{Z} [ sum_{} P(Z|X) ] [ sum_{} [ sum_{X} P(Y|X,Z) P(X) ] ] ]
Expected: [ sum_{Z} [ sum_{} P(Z|X) ] [ sum_{} [ sum_{X} P(X) P(Y|X,Z) ] ] ]

F
======================================================================
FAIL: test_figure_2b (__main__.TestIdentify)
Test Figure 2B.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_id_alg.py", line 63, in test_figure_2b
    self.assert_identify(grammar.parseString(expr)[0], graph, Y@X)
  File "test_id_alg.py", line 38, in assert_identify
    self.assertEqual(expression, identify(graph, query))
AssertionError: Sum(e[66 chars]ame='Z'),), parents=(Variable(name='X'),))), P[124 chars]'),)) != Sum(e[66 chars]ame='Y'),), parents=(Variable(name='X'), Varia[124 chars]'),))

======================================================================
FAIL: test_figure_2c (__main__.TestIdentify)
Test Figure 2C.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_id_alg.py", line 79, in test_figure_2c
    self.assert_identify(grammar.parseString(expr)[0], graph, Y@X)
  File "test_id_alg.py", line 38, in assert_identify
    self.assertEqual(expression, identify(graph, query))
AssertionError: Sum(e[66 chars]ame='Z'),), parents=())), P(Distribution(child[105 chars]'),)) != Sum(e[66 chars]ame='Y'),), parents=(Variable(name='X'), Varia[105 chars]'),))

======================================================================
FAIL: test_figure_2e (__main__.TestIdentify)
Test Figure 2E.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_id_alg.py", line 115, in test_figure_2e
    self.assert_identify(grammar.parseString(expr)[0], graph, Y@X)
  File "test_id_alg.py", line 38, in assert_identify
    self.assertEqual(expression, identify(graph, query))
AssertionError: Sum(e[224 chars]ame='X'),), parents=())), P(Distribution(child[150 chars]'),)) != Sum(e[224 chars]ame='Y'),), parents=(Variable(name='X'), Varia[150 chars]'),))

----------------------------------------------------------------------
Ran 5 tests in 0.024s

FAILED (failures=3)
(anaconda3-2020.11) bash-3.2$ python test_id_alg.py 

[ sum_{} P(Y|X) ]

.
[ sum_{Z} P(Z|X) P(Y|X,Z) ]

.
[ sum_{Z} P(Z) P(Y|X,Z) ]

.
[ sum_{Z} [ sum_{} P(Y|X,Z) ] [ sum_{} [ sum_{X,Y} P(X,Y,Z) ] ] ]

.
ID output: [ sum_{Z} [ sum_{} P(Z|X) ] [ sum_{} [ sum_{X} P(Y|X,Z) P(X) ] ] ]
Expected: [ sum_{Z} [ sum_{} P(Z|X) ] [ sum_{} [ sum_{X} P(X) P(Y|X,Z) ] ] ]

F
======================================================================
FAIL: test_figure_2e (__main__.TestIdentify)
Test Figure 2E.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_id_alg.py", line 115, in test_figure_2e
    self.assert_identify(grammar.parseString(expr)[0], graph, Y@X)
  File "test_id_alg.py", line 38, in assert_identify
    self.assertEqual(expression, identify(graph, query))
AssertionError: Sum(e[224 chars]ame='X'),), parents=())), P(Distribution(child[150 chars]'),)) != Sum(e[224 chars]ame='Y'),), parents=(Variable(name='X'), Varia[150 chars]'),))

----------------------------------------------------------------------
Ran 5 tests in 0.022s

FAILED (failures=1)
(anaconda3-2020.11) bash-3.2$ python test_id_alg.py 

[ sum_{} P(Y|X) ]

.
[ sum_{Z} P(Z|X) P(Y|X,Z) ]

.
[ sum_{Z} P(Z) P(Y|X,Z) ]

.
[ sum_{Z} [ sum_{} P(Y|X,Z) ] [ sum_{} [ sum_{X,Y} P(X,Y,Z) ] ] ]

.
ID output: [ sum_{Z} [ sum_{} P(Z|X) ] [ sum_{} [ sum_{X} P(X) P(Y|X,Z) ] ] ]
Expected: [ sum_{Z} [ sum_{} P(Z|X) ] [ sum_{} [ sum_{X} P(X) P(Y|X,Z) ] ] ]

.
----------------------------------------------------------------------
Ran 5 tests in 0.024s

OK
(anaconda3-2020.11) bash-3.2$ 
```

**Comment by cthoyt** [comment]
This was solved by #45
